// Generated by gencpp from file embedded_mas_examples/SumArrayRequest.msg
// DO NOT EDIT!


#ifndef EMBEDDED_MAS_EXAMPLES_MESSAGE_SUMARRAYREQUEST_H
#define EMBEDDED_MAS_EXAMPLES_MESSAGE_SUMARRAYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace embedded_mas_examples
{
template <class ContainerAllocator>
struct SumArrayRequest_
{
  typedef SumArrayRequest_<ContainerAllocator> Type;

  SumArrayRequest_()
    : v()  {
    }
  SumArrayRequest_(const ContainerAllocator& _alloc)
    : v(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int64_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int64_t>> _v_type;
  _v_type v;





  typedef boost::shared_ptr< ::embedded_mas_examples::SumArrayRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::embedded_mas_examples::SumArrayRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SumArrayRequest_

typedef ::embedded_mas_examples::SumArrayRequest_<std::allocator<void> > SumArrayRequest;

typedef boost::shared_ptr< ::embedded_mas_examples::SumArrayRequest > SumArrayRequestPtr;
typedef boost::shared_ptr< ::embedded_mas_examples::SumArrayRequest const> SumArrayRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::embedded_mas_examples::SumArrayRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::embedded_mas_examples::SumArrayRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::embedded_mas_examples::SumArrayRequest_<ContainerAllocator1> & lhs, const ::embedded_mas_examples::SumArrayRequest_<ContainerAllocator2> & rhs)
{
  return lhs.v == rhs.v;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::embedded_mas_examples::SumArrayRequest_<ContainerAllocator1> & lhs, const ::embedded_mas_examples::SumArrayRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace embedded_mas_examples

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::embedded_mas_examples::SumArrayRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::embedded_mas_examples::SumArrayRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::embedded_mas_examples::SumArrayRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::embedded_mas_examples::SumArrayRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::embedded_mas_examples::SumArrayRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::embedded_mas_examples::SumArrayRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::embedded_mas_examples::SumArrayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "31ce150554f9111067abff354df61d2a";
  }

  static const char* value(const ::embedded_mas_examples::SumArrayRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x31ce150554f91110ULL;
  static const uint64_t static_value2 = 0x67abff354df61d2aULL;
};

template<class ContainerAllocator>
struct DataType< ::embedded_mas_examples::SumArrayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "embedded_mas_examples/SumArrayRequest";
  }

  static const char* value(const ::embedded_mas_examples::SumArrayRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::embedded_mas_examples::SumArrayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64[] v\n"
;
  }

  static const char* value(const ::embedded_mas_examples::SumArrayRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::embedded_mas_examples::SumArrayRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.v);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SumArrayRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::embedded_mas_examples::SumArrayRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::embedded_mas_examples::SumArrayRequest_<ContainerAllocator>& v)
  {
    s << indent << "v[]" << std::endl;
    for (size_t i = 0; i < v.v.size(); ++i)
    {
      s << indent << "  v[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.v[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // EMBEDDED_MAS_EXAMPLES_MESSAGE_SUMARRAYREQUEST_H
