// Generated by gencpp from file embedded_mas_examples/SumArrayResponse.msg
// DO NOT EDIT!


#ifndef EMBEDDED_MAS_EXAMPLES_MESSAGE_SUMARRAYRESPONSE_H
#define EMBEDDED_MAS_EXAMPLES_MESSAGE_SUMARRAYRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace embedded_mas_examples
{
template <class ContainerAllocator>
struct SumArrayResponse_
{
  typedef SumArrayResponse_<ContainerAllocator> Type;

  SumArrayResponse_()
    : sum(0)  {
    }
  SumArrayResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int64_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::embedded_mas_examples::SumArrayResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::embedded_mas_examples::SumArrayResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SumArrayResponse_

typedef ::embedded_mas_examples::SumArrayResponse_<std::allocator<void> > SumArrayResponse;

typedef boost::shared_ptr< ::embedded_mas_examples::SumArrayResponse > SumArrayResponsePtr;
typedef boost::shared_ptr< ::embedded_mas_examples::SumArrayResponse const> SumArrayResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::embedded_mas_examples::SumArrayResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::embedded_mas_examples::SumArrayResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::embedded_mas_examples::SumArrayResponse_<ContainerAllocator1> & lhs, const ::embedded_mas_examples::SumArrayResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::embedded_mas_examples::SumArrayResponse_<ContainerAllocator1> & lhs, const ::embedded_mas_examples::SumArrayResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace embedded_mas_examples

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::embedded_mas_examples::SumArrayResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::embedded_mas_examples::SumArrayResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::embedded_mas_examples::SumArrayResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::embedded_mas_examples::SumArrayResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::embedded_mas_examples::SumArrayResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::embedded_mas_examples::SumArrayResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::embedded_mas_examples::SumArrayResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b88405221c77b1878a3cbbfff53428d7";
  }

  static const char* value(const ::embedded_mas_examples::SumArrayResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb88405221c77b187ULL;
  static const uint64_t static_value2 = 0x8a3cbbfff53428d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::embedded_mas_examples::SumArrayResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "embedded_mas_examples/SumArrayResponse";
  }

  static const char* value(const ::embedded_mas_examples::SumArrayResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::embedded_mas_examples::SumArrayResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 sum\n"
"\n"
;
  }

  static const char* value(const ::embedded_mas_examples::SumArrayResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::embedded_mas_examples::SumArrayResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SumArrayResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::embedded_mas_examples::SumArrayResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::embedded_mas_examples::SumArrayResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int64_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EMBEDDED_MAS_EXAMPLES_MESSAGE_SUMARRAYRESPONSE_H
