// Generated by gencpp from file embedded_mas_examples/SumArray.msg
// DO NOT EDIT!


#ifndef EMBEDDED_MAS_EXAMPLES_MESSAGE_SUMARRAY_H
#define EMBEDDED_MAS_EXAMPLES_MESSAGE_SUMARRAY_H

#include <ros/service_traits.h>


#include <embedded_mas_examples/SumArrayRequest.h>
#include <embedded_mas_examples/SumArrayResponse.h>


namespace embedded_mas_examples
{

struct SumArray
{

typedef SumArrayRequest Request;
typedef SumArrayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SumArray
} // namespace embedded_mas_examples


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::embedded_mas_examples::SumArray > {
  static const char* value()
  {
    return "06b98b511eb27f6208b0367ed1441011";
  }

  static const char* value(const ::embedded_mas_examples::SumArray&) { return value(); }
};

template<>
struct DataType< ::embedded_mas_examples::SumArray > {
  static const char* value()
  {
    return "embedded_mas_examples/SumArray";
  }

  static const char* value(const ::embedded_mas_examples::SumArray&) { return value(); }
};


// service_traits::MD5Sum< ::embedded_mas_examples::SumArrayRequest> should match
// service_traits::MD5Sum< ::embedded_mas_examples::SumArray >
template<>
struct MD5Sum< ::embedded_mas_examples::SumArrayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::embedded_mas_examples::SumArray >::value();
  }
  static const char* value(const ::embedded_mas_examples::SumArrayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::embedded_mas_examples::SumArrayRequest> should match
// service_traits::DataType< ::embedded_mas_examples::SumArray >
template<>
struct DataType< ::embedded_mas_examples::SumArrayRequest>
{
  static const char* value()
  {
    return DataType< ::embedded_mas_examples::SumArray >::value();
  }
  static const char* value(const ::embedded_mas_examples::SumArrayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::embedded_mas_examples::SumArrayResponse> should match
// service_traits::MD5Sum< ::embedded_mas_examples::SumArray >
template<>
struct MD5Sum< ::embedded_mas_examples::SumArrayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::embedded_mas_examples::SumArray >::value();
  }
  static const char* value(const ::embedded_mas_examples::SumArrayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::embedded_mas_examples::SumArrayResponse> should match
// service_traits::DataType< ::embedded_mas_examples::SumArray >
template<>
struct DataType< ::embedded_mas_examples::SumArrayResponse>
{
  static const char* value()
  {
    return DataType< ::embedded_mas_examples::SumArray >::value();
  }
  static const char* value(const ::embedded_mas_examples::SumArrayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EMBEDDED_MAS_EXAMPLES_MESSAGE_SUMARRAY_H
