/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package serviceRequest;

import embedded.mas.bridges.ros.ros.RosBridge;

public class App {


    public static void main(String[] args) {
         RosBridge bridge = new RosBridge();
	bridge.connect("ws://localhost:9090", true);
	String serviceName = "/turtle1/teleport_relative";
	String serviceArguments = "{\"linear\":1,\"angular\":1}";
	bridge.sendRawMessage("{\"op\": \"call_service\", \"service\": \""+ serviceName +"\", \"args\": "+ serviceArguments +",\"id\":\"1\"}");
    }
}
